### ISSUE TITLE
Provide builds for Linux as well

### ISSUE THREAD

**Issue by tbrent** [reserve-protocol/poke#5]
I put some effort into doing this previously and ran into an issue where the version of go-ethereum we're using excludes an important file due to a "javascript" build tag, preventing the build from completing. I think the solution is upgrading the version of go-ethereum we're using. This involves some code change from our side as well.

**Comment by jeremyschlatter** [comment]
go-ethereum bump here: https://github.com/reserve-protocol/poke/pull/7

**Comment by tbrent** [comment]
Was able to get equinox to comply this time for linux_amd64. Closing.
